




```{r}
  dame_estadistico = function(muestra){
return(sum(muestra > 3))
}

dame_estadistico(muestra = sample(x = 1:6, size = 25, replace = T))
sum(dame_estadistico(muestra = sample(x = 1:6, size = 25, replace = T)))
mean(dame_estadistico(muestra = sample(x = 1:6, size = 25, replace = T)))


muestras = replicate(1000, mean(dame_estadistico(muestra = sample(x = 1:6, 
                                                                  size = 25, 
                                                                  replace = T))))
muestras

hist(muestras, freq = F) #Al poner freq = FALSE, obtengo un grafico de densidad en vez de distribucion
points(x = 5:25, 
       dbinom(x = 5:25, size = 25, prob = 0.5), col = "red")

qbinom(0.975, 25, 0.5)
qbinom(0.025, 25, 0.5)

```

```{r}

```
```{r}
cargadoen_6 = function(x) {
  return(sample(1:6,
                size = 25, 
                replace = T, 
                prob = c(0.1,0.1,0.1,0.1,0.1,0.5)))
  }

cargadoen1_6 = function(x) {
  return(sample(2:5, 
                size = 25,
                replace = T))
}

cargadoen_impar = function(x) {
  return(sample(seq(from = 1, to = 6, by = 2),
                replace = T,
                size = 25))
}
```


```{r}
par(mfrow = c(2, 2))

hist(muestras, freq = T)

muestras_cargado_6 = replicate(1000, mean(dame_estadistico(muestra = cargadoen_6())))
hist(muestras_cargado_6, freq = T)

muestras_cargado_1_6 = replicate(1000, mean(dame_estadistico(muestra = cargadoen1_6())))
hist(muestras_cargado_1_6, freq = T)

muestras_cargado_impar = replicate(1000, mean(dame_estadistico(muestra = cargadoen_impar())))
hist(muestras_cargado_impar, freq = T)
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

